import { applyDiff } from "./diff/parse"
import { expandRangeRefs, type FileReader } from "./resolve/range-expand"
import { resolveFuzzyPatterns } from "./resolve/fuzzy-match"
import {
  repairJsonNewlines,
  toExtraPretty,
  fromExtraPretty,
  PrettyJsonError,
} from "./resolve/json-expand"
import { stripPendingRefs } from "~/lib/files/pending-refs"
import { parseCodeBlocks } from "~/lib/data-blocks/parse"
import { fillMissingIds, buildGeneratedIdsList, type GeneratedId } from "~/lib/data-blocks/uuid"
import {
  validateMarkdownBlocks,
  extractProse,
  type ValidationError,
} from "~/lib/data-blocks/validate"
import { stampActors } from "~/lib/data-blocks/actor"
import type { ValidationContext } from "~/lib/data-blocks/validate"
import { getFiles } from "~/lib/files/store"
import { getAllCodes } from "~/domain/data-blocks/callout/codes/selectors"
import { getTagDefinitions } from "~/domain/data-blocks/settings/tags/selectors"

type FileResult =
  | { path: string; status: "ok"; content: string; generatedIds?: GeneratedId[] }
  | { path: string; status: "error"; error: string; blockErrors?: ValidationError[] }

const isMdFile = (path: string): boolean => path.endsWith(".md")
const isJsonBlock = (language: string): boolean => language.startsWith("json")

const ensureTrailingNewline = (s: string): string =>
  s.length > 0 && !s.endsWith("\n") ? s + "\n" : s

const repairJsonBlocks = (markdown: string): string => {
  const blocks = parseCodeBlocks(markdown).filter((b) => isJsonBlock(b.language))
  if (blocks.length === 0) return markdown

  let result = markdown
  let offset = 0

  for (const block of blocks) {
    const repaired = repairJsonNewlines(block.content)
    if (repaired === block.content) continue

    const blockStart = block.start + offset
    const blockEnd = block.end + offset
    const original = result.slice(blockStart, blockEnd)
    const replaced = original.replace(block.content, repaired)

    result = result.slice(0, blockStart) + replaced + result.slice(blockEnd)
    offset += replaced.length - original.length
  }

  return result
}

const buildValidationContext = (markdown: string): ValidationContext => ({
  documentProse: extractProse(markdown),
  availableCodes: getAllCodes(getFiles()).map((c) => ({ id: c.id, name: c.title })),
  availableTags: getTagDefinitions(getFiles()).map((t) => ({ id: t.id, label: t.label })),
})

const formatBlockErrors = (errors: ValidationError[]): string =>
  errors
    .map((e) => {
      const location = e.field ? `${e.block}.${e.field}` : e.block
      const hint = e.hint ? ` Available: ${JSON.stringify(e.hint)}` : ""
      const current = e.currentBlock ? `\nCurrent block:\n${e.currentBlock}` : ""
      return `${location}: ${e.message}${hint}${current}`
    })
    .join("\n")

interface ApplyMdPatchOptions {
  skipImmutableCheck?: boolean
  skipCodeValidation?: boolean
  placeholderIds?: Record<string, string>
  actor?: "ai" | "user"
}

interface FinalizeContentOptions {
  original: string
  actor?: "ai" | "user"
  skipImmutableCheck?: boolean
  skipCodeValidation?: boolean
  placeholderIds?: Record<string, string>
}

const toPretty = (raw: string): string => toExtraPretty(stripPendingRefs(raw))

const buildFileReader =
  (currentPath: string, currentContent: string): FileReader =>
  (p) => {
    const raw = p === currentPath ? currentContent : getFiles()[p]
    return raw !== undefined ? toPretty(raw) : undefined
  }

export const finalizeContent = (
  path: string,
  content: string,
  options: FinalizeContentOptions
): FileResult => {
  const { content: filledContent, generated: autoGenerated } = fillMissingIds(
    content,
    options.original
  )
  const stampedContent = options.actor
    ? stampActors(options.original, filledContent, options.actor)
    : filledContent

  const context = buildValidationContext(stampedContent)
  const validation = validateMarkdownBlocks(stampedContent, {
    path,
    context,
    original: options.original,
    skipImmutableCheck: options.skipImmutableCheck,
  })

  if (!validation.valid) {
    if (options.skipCodeValidation) {
      console.warn(
        `[patch] validation warnings for "${path}":`,
        formatBlockErrors(validation.errors)
      )
    } else {
      return {
        path,
        status: "error",
        error: formatBlockErrors(validation.errors),
        blockErrors: validation.errors,
      }
    }
  }

  const generatedIds = buildGeneratedIdsList(
    options.placeholderIds ?? {},
    autoGenerated,
    stampedContent
  )

  return {
    path,
    status: "ok",
    content: stampedContent,
    ...(generatedIds.length > 0 && { generatedIds }),
  }
}

const applyMdPatch = (
  path: string,
  content: string,
  patch: string,
  options: ApplyMdPatchOptions = {}
): FileResult => {
  if (content === "" && patch === "") {
    return { path, status: "ok", content: "" }
  }

  const rangeResult = expandRangeRefs(patch, buildFileReader(path, content), path)
  if (!rangeResult.ok) return { path, status: "error", error: rangeResult.error }

  const { patch: resolvedPatch, unresolved } = resolveFuzzyPatterns(rangeResult.patch, content)
  if (unresolved.length > 0) {
    return {
      path,
      status: "error",
      error: `FUZZY patterns not found: ${unresolved.map((s) => `"${s}"`).join(", ")}. Use exact text from the document instead of paraphrasing.`,
    }
  }

  const prettyContent = toExtraPretty(stripPendingRefs(content))
  const diffResult = applyDiff(prettyContent, resolvedPatch)
  if (!diffResult.ok) {
    return { path, status: "error", error: diffResult.error }
  }

  let collapsedContent: string
  try {
    collapsedContent = fromExtraPretty(diffResult.content)
  } catch (e) {
    if (e instanceof PrettyJsonError) {
      return { path, status: "error", error: e.message }
    }
    throw e
  }

  const repairedContent = ensureTrailingNewline(repairJsonBlocks(collapsedContent))
  return finalizeContent(path, repairedContent, { original: content, ...options })
}

interface ApplyFilePatchOptions {
  skipImmutableCheck?: boolean
  skipCodeValidation?: boolean
  placeholderIds?: Record<string, string>
  actor?: "ai" | "user"
}

export const applyFilePatch = (
  path: string,
  content: string,
  patch: string,
  options: ApplyFilePatchOptions = {}
): FileResult =>
  isMdFile(path)
    ? applyMdPatch(path, content, patch, options)
    : { path, status: "error", error: `only .md files allowed: ${path}` }
