export type { Annotation, ResolvedAnnotation, OverlapSegment } from "./types"
export type { TextPosition } from "./text"
export { findTextPosition, resolveTextAnnotations } from "./text"
export { segmentByOverlap } from "./overlap"
export { createBarberPoleGradient, createBackground } from "./gradient"
