import type { ComponentType } from "react"
import type { IconName } from "~/domain/icons"
import {
  FeatherActivity,
  FeatherAnchor,
  FeatherArchive,
  FeatherAtSign,
  FeatherAtom,
  FeatherAward,
  FeatherBaby,
  FeatherBarChart,
  FeatherBeaker,
  FeatherBell,
  FeatherBird,
  FeatherBook,
  FeatherBookOpen,
  FeatherBookText,
  FeatherBookmark,
  FeatherBot,
  FeatherBox,
  FeatherBrain,
  FeatherBrainCircuit,
  FeatherBriefcase,
  FeatherBug,
  FeatherBuilding,
  FeatherCalendar,
  FeatherCalendarCheck,
  FeatherCalendarDays,
  FeatherCamera,
  FeatherCat,
  FeatherChartLine,
  FeatherChartNetwork,
  FeatherChartPie,
  FeatherCheckCircle,
  FeatherChurch,
  FeatherClipboard,
  FeatherClipboardList,
  FeatherClock,
  FeatherCloud,
  FeatherClover,
  FeatherCode,
  FeatherCoffee,
  FeatherCompass,
  FeatherContact,
  FeatherCrown,
  FeatherDatabase,
  FeatherDiamond,
  FeatherDna,
  FeatherDog,
  FeatherDownload,
  FeatherDroplet,
  FeatherEar,
  FeatherEarth,
  FeatherExternalLink,
  FeatherEye,
  FeatherFeather,
  FeatherFile,
  FeatherFileChartLine,
  FeatherFileCheck,
  FeatherFileCode,
  FeatherFileSearch,
  FeatherFileSpreadsheet,
  FeatherFileText,
  FeatherFilm,
  FeatherFilter,
  FeatherFingerprint,
  FeatherFish,
  FeatherFlag,
  FeatherFlame,
  FeatherFlaskConical,
  FeatherFlaskRound,
  FeatherFlower,
  FeatherFocus,
  FeatherFolder,
  FeatherFolderOpen,
  FeatherFolderSearch,
  FeatherFunnel,
  FeatherGauge,
  FeatherGavel,
  FeatherGem,
  FeatherGift,
  FeatherGlasses,
  FeatherGlobe,
  FeatherGraduationCap,
  FeatherGrid,
  FeatherGroup,
  FeatherHammer,
  FeatherHandshake,
  FeatherHash,
  FeatherHeadphones,
  FeatherHeart,
  FeatherHeartPulse,
  FeatherHelpCircle,
  FeatherHighlighter,
  FeatherHistory,
  FeatherHome,
  FeatherHourglass,
  FeatherImage,
  FeatherInbox,
  FeatherInfinity,
  FeatherInfo,
  FeatherKanban,
  FeatherKey,
  FeatherLandmark,
  FeatherLanguages,
  FeatherLaptop,
  FeatherLayers,
  FeatherLeaf,
  FeatherLibrary,
  FeatherLightbulb,
  FeatherLink,
  FeatherList,
  FeatherListCheck,
  FeatherLock,
  FeatherMail,
  FeatherMap,
  FeatherMapPin,
  FeatherMedal,
  FeatherMegaphone,
  FeatherMessageCircle,
  FeatherMessageSquare,
  FeatherMic,
  FeatherMicroscope,
  FeatherMilestone,
  FeatherMonitor,
  FeatherMoon,
  FeatherMountain,
  FeatherMusic,
  FeatherNavigation,
  FeatherNetwork,
  FeatherNewspaper,
  FeatherNotebook,
  FeatherNotebookPen,
  FeatherOrbit,
  FeatherPackage,
  FeatherPalette,
  FeatherPaperclip,
  FeatherPawPrint,
  FeatherPen,
  FeatherPencil,
  FeatherPhone,
  FeatherPill,
  FeatherPin,
  FeatherPlus,
  FeatherPodcast,
  FeatherPower,
  FeatherPresentation,
  FeatherPrinter,
  FeatherPuzzle,
  FeatherQuote,
  FeatherRabbit,
  FeatherRadiation,
  FeatherRainbow,
  FeatherRocket,
  FeatherRoute,
  FeatherSave,
  FeatherScale,
  FeatherSchool,
  FeatherScissors,
  FeatherScroll,
  FeatherScrollText,
  FeatherSearch,
  FeatherSend,
  FeatherSettings,
  FeatherShapes,
  FeatherShare,
  FeatherShield,
  FeatherSigma,
  FeatherSignpost,
  FeatherSliders,
  FeatherSmartphone,
  FeatherSnail,
  FeatherSnowflake,
  FeatherSparkles,
  FeatherSpeech,
  FeatherSprout,
  FeatherSquirrel,
  FeatherStar,
  FeatherStethoscope,
  FeatherStickyNote,
  FeatherSun,
  FeatherSunrise,
  FeatherSunset,
  FeatherSyringe,
  FeatherTable,
  FeatherTag,
  FeatherTags,
  FeatherTarget,
  FeatherTelescope,
  FeatherTerminal,
  FeatherTestTube,
  FeatherText,
  FeatherTextQuote,
  FeatherTheater,
  FeatherThermometer,
  FeatherTimer,
  FeatherTool,
  FeatherTrash,
  FeatherTreeDeciduous,
  FeatherTreePine,
  FeatherTrees,
  FeatherTrendingUp,
  FeatherTrophy,
  FeatherTurtle,
  FeatherUmbrella,
  FeatherUniversity,
  FeatherUnlock,
  FeatherUpload,
  FeatherUser,
  FeatherUsers,
  FeatherVerified,
  FeatherVideo,
  FeatherVote,
  FeatherWand,
  FeatherWaves,
  FeatherWifi,
  FeatherWind,
  FeatherWorkflow,
  FeatherWrench,
  FeatherZap,
} from "@subframe/core"

export type FeatherIcon = ComponentType<{ className?: string }>

const FEATHER_ICONS: Record<IconName, FeatherIcon> = {
  "activity": FeatherActivity,
  "anchor": FeatherAnchor,
  "archive": FeatherArchive,
  "at-sign": FeatherAtSign,
  "atom": FeatherAtom,
  "award": FeatherAward,
  "baby": FeatherBaby,
  "bar-chart": FeatherBarChart,
  "beaker": FeatherBeaker,
  "bell": FeatherBell,
  "bird": FeatherBird,
  "book": FeatherBook,
  "book-open": FeatherBookOpen,
  "book-text": FeatherBookText,
  "bookmark": FeatherBookmark,
  "bot": FeatherBot,
  "box": FeatherBox,
  "brain": FeatherBrain,
  "brain-circuit": FeatherBrainCircuit,
  "briefcase": FeatherBriefcase,
  "bug": FeatherBug,
  "building": FeatherBuilding,
  "calendar": FeatherCalendar,
  "calendar-check": FeatherCalendarCheck,
  "calendar-days": FeatherCalendarDays,
  "camera": FeatherCamera,
  "cat": FeatherCat,
  "chart-line": FeatherChartLine,
  "chart-network": FeatherChartNetwork,
  "chart-pie": FeatherChartPie,
  "check-circle": FeatherCheckCircle,
  "church": FeatherChurch,
  "clipboard": FeatherClipboard,
  "clipboard-list": FeatherClipboardList,
  "clock": FeatherClock,
  "cloud": FeatherCloud,
  "clover": FeatherClover,
  "code": FeatherCode,
  "coffee": FeatherCoffee,
  "compass": FeatherCompass,
  "contact": FeatherContact,
  "crown": FeatherCrown,
  "database": FeatherDatabase,
  "diamond": FeatherDiamond,
  "dna": FeatherDna,
  "dog": FeatherDog,
  "download": FeatherDownload,
  "droplet": FeatherDroplet,
  "ear": FeatherEar,
  "earth": FeatherEarth,
  "external-link": FeatherExternalLink,
  "eye": FeatherEye,
  "feather": FeatherFeather,
  "file": FeatherFile,
  "file-chart-line": FeatherFileChartLine,
  "file-check": FeatherFileCheck,
  "file-code": FeatherFileCode,
  "file-search": FeatherFileSearch,
  "file-spreadsheet": FeatherFileSpreadsheet,
  "file-text": FeatherFileText,
  "film": FeatherFilm,
  "filter": FeatherFilter,
  "fingerprint": FeatherFingerprint,
  "fish": FeatherFish,
  "flag": FeatherFlag,
  "flame": FeatherFlame,
  "flask-conical": FeatherFlaskConical,
  "flask-round": FeatherFlaskRound,
  "flower": FeatherFlower,
  "focus": FeatherFocus,
  "folder": FeatherFolder,
  "folder-open": FeatherFolderOpen,
  "folder-search": FeatherFolderSearch,
  "funnel": FeatherFunnel,
  "gauge": FeatherGauge,
  "gavel": FeatherGavel,
  "gem": FeatherGem,
  "gift": FeatherGift,
  "glasses": FeatherGlasses,
  "globe": FeatherGlobe,
  "graduation-cap": FeatherGraduationCap,
  "grid": FeatherGrid,
  "group": FeatherGroup,
  "hammer": FeatherHammer,
  "handshake": FeatherHandshake,
  "hash": FeatherHash,
  "headphones": FeatherHeadphones,
  "heart": FeatherHeart,
  "heart-pulse": FeatherHeartPulse,
  "help-circle": FeatherHelpCircle,
  "highlighter": FeatherHighlighter,
  "history": FeatherHistory,
  "home": FeatherHome,
  "hourglass": FeatherHourglass,
  "image": FeatherImage,
  "inbox": FeatherInbox,
  "infinity": FeatherInfinity,
  "info": FeatherInfo,
  "kanban": FeatherKanban,
  "key": FeatherKey,
  "landmark": FeatherLandmark,
  "languages": FeatherLanguages,
  "laptop": FeatherLaptop,
  "layers": FeatherLayers,
  "leaf": FeatherLeaf,
  "library": FeatherLibrary,
  "lightbulb": FeatherLightbulb,
  "link": FeatherLink,
  "list": FeatherList,
  "list-check": FeatherListCheck,
  "lock": FeatherLock,
  "mail": FeatherMail,
  "map": FeatherMap,
  "map-pin": FeatherMapPin,
  "medal": FeatherMedal,
  "megaphone": FeatherMegaphone,
  "message-circle": FeatherMessageCircle,
  "message-square": FeatherMessageSquare,
  "mic": FeatherMic,
  "microscope": FeatherMicroscope,
  "milestone": FeatherMilestone,
  "monitor": FeatherMonitor,
  "moon": FeatherMoon,
  "mountain": FeatherMountain,
  "music": FeatherMusic,
  "navigation": FeatherNavigation,
  "network": FeatherNetwork,
  "newspaper": FeatherNewspaper,
  "notebook": FeatherNotebook,
  "notebook-pen": FeatherNotebookPen,
  "orbit": FeatherOrbit,
  "package": FeatherPackage,
  "palette": FeatherPalette,
  "paperclip": FeatherPaperclip,
  "paw-print": FeatherPawPrint,
  "pen": FeatherPen,
  "pencil": FeatherPencil,
  "phone": FeatherPhone,
  "pill": FeatherPill,
  "pin": FeatherPin,
  "plus": FeatherPlus,
  "podcast": FeatherPodcast,
  "power": FeatherPower,
  "presentation": FeatherPresentation,
  "printer": FeatherPrinter,
  "puzzle": FeatherPuzzle,
  "quote": FeatherQuote,
  "rabbit": FeatherRabbit,
  "radiation": FeatherRadiation,
  "rainbow": FeatherRainbow,
  "rocket": FeatherRocket,
  "route": FeatherRoute,
  "save": FeatherSave,
  "scale": FeatherScale,
  "school": FeatherSchool,
  "scissors": FeatherScissors,
  "scroll": FeatherScroll,
  "scroll-text": FeatherScrollText,
  "search": FeatherSearch,
  "send": FeatherSend,
  "settings": FeatherSettings,
  "shapes": FeatherShapes,
  "share": FeatherShare,
  "shield": FeatherShield,
  "sigma": FeatherSigma,
  "signpost": FeatherSignpost,
  "sliders": FeatherSliders,
  "smartphone": FeatherSmartphone,
  "snail": FeatherSnail,
  "snowflake": FeatherSnowflake,
  "sparkles": FeatherSparkles,
  "speech": FeatherSpeech,
  "sprout": FeatherSprout,
  "squirrel": FeatherSquirrel,
  "star": FeatherStar,
  "stethoscope": FeatherStethoscope,
  "sticky-note": FeatherStickyNote,
  "sun": FeatherSun,
  "sunrise": FeatherSunrise,
  "sunset": FeatherSunset,
  "syringe": FeatherSyringe,
  "table": FeatherTable,
  "tag": FeatherTag,
  "tags": FeatherTags,
  "target": FeatherTarget,
  "telescope": FeatherTelescope,
  "terminal": FeatherTerminal,
  "test-tube": FeatherTestTube,
  "text": FeatherText,
  "text-quote": FeatherTextQuote,
  "theater": FeatherTheater,
  "thermometer": FeatherThermometer,
  "timer": FeatherTimer,
  "tool": FeatherTool,
  "trash": FeatherTrash,
  "tree-deciduous": FeatherTreeDeciduous,
  "tree-pine": FeatherTreePine,
  "trees": FeatherTrees,
  "trending-up": FeatherTrendingUp,
  "trophy": FeatherTrophy,
  "turtle": FeatherTurtle,
  "umbrella": FeatherUmbrella,
  "university": FeatherUniversity,
  "unlock": FeatherUnlock,
  "upload": FeatherUpload,
  "user": FeatherUser,
  "users": FeatherUsers,
  "verified": FeatherVerified,
  "video": FeatherVideo,
  "vote": FeatherVote,
  "wand": FeatherWand,
  "waves": FeatherWaves,
  "wifi": FeatherWifi,
  "wind": FeatherWind,
  "workflow": FeatherWorkflow,
  "wrench": FeatherWrench,
  "zap": FeatherZap,
}

export const resolveFeatherIcon = (name: string): FeatherIcon =>
  FEATHER_ICONS[name as IconName] ?? FeatherHash
