export { FileHeader } from "./FileHeader"
export { EditorToolbar } from "./EditorToolbar"
export { EditorDocumentProvider, useEditorDocument } from "./context"
export type { EditorDocumentInfo } from "./context"
export { SpotlightOverlay } from "./Spotlight"
export { ScrollGutter } from "./ScrollGutter"
