import type { ComponentType } from "react"
import type { IconName } from "./icons"
import {
  Activity,
  Amphora,
  Anchor,
  Antenna,
  Apple,
  Archive,
  AtSign,
  Atom,
  Award,
  Baby,
  Backpack,
  Bandage,
  Banknote,
  BarChart,
  Beaker,
  Bell,
  Binary,
  Binoculars,
  Bird,
  Bone,
  Book,
  BookMarked,
  BookOpen,
  BookOpenCheck,
  BookText,
  Bookmark,
  Bot,
  Box,
  Brain,
  BrainCircuit,
  BrainCog,
  Briefcase,
  BriefcaseMedical,
  Bug,
  Building,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarDays,
  Camera,
  Castle,
  Cat,
  ChartBarStacked,
  ChartLine,
  ChartNetwork,
  ChartPie,
  ChartScatter,
  CheckCircle,
  Cherry,
  Church,
  CircleDot,
  CircuitBoard,
  Clapperboard,
  Clipboard,
  ClipboardList,
  Clock,
  Cloud,
  CloudRain,
  CloudSun,
  Clover,
  Code,
  Coffee,
  Coins,
  Compass,
  Construction,
  Contact,
  CookingPot,
  Cpu,
  Crosshair,
  Crown,
  Database,
  Diamond,
  Dna,
  Dog,
  Download,
  DraftingCompass,
  Drama,
  Droplet,
  Dumbbell,
  Ear,
  Earth,
  ExternalLink,
  Eye,
  Factory,
  Feather,
  File,
  FileChartLine,
  FileCheck,
  FileCode,
  FileSearch,
  FileSpreadsheet,
  FileText,
  Film,
  Filter,
  Fingerprint,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  FlaskRound,
  Flower,
  Focus,
  Folder,
  FolderOpen,
  FolderSearch,
  Footprints,
  Frown,
  Funnel,
  Gauge,
  Gavel,
  Gem,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Grape,
  Grid,
  Group,
  Guitar,
  Hammer,
  HandCoins,
  HandHeart,
  Handshake,
  HardDrive,
  HardHat,
  Hash,
  Headphones,
  Heart,
  HeartPulse,
  HelpCircle,
  HelpingHand,
  Highlighter,
  History,
  Home,
  Hospital,
  Hourglass,
  Image,
  Inbox,
  Infinity as InfinityIcon,
  Info,
  Kanban,
  Key,
  Landmark,
  Languages,
  Laptop,
  Layers,
  Leaf,
  Lectern,
  Library,
  Lightbulb,
  Link,
  List,
  ListCheck,
  Lock,
  Mail,
  Map,
  MapPin,
  Medal,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Mic,
  Microchip,
  Microscope,
  Milestone,
  Monitor,
  Moon,
  Mountain,
  Music,
  Navigation,
  Network,
  Newspaper,
  Notebook,
  NotebookPen,
  Orbit,
  Origami,
  Package,
  Paintbrush,
  Palette,
  Paperclip,
  PawPrint,
  Pen,
  Pencil,
  Percent,
  PersonStanding,
  Phone,
  Pi,
  Piano,
  PiggyBank,
  Pill,
  Pin,
  Plus,
  Podcast,
  Power,
  Presentation,
  Printer,
  Puzzle,
  Quote,
  Rabbit,
  Radar,
  Radiation,
  Radio,
  RadioTower,
  Rainbow,
  Rat,
  Receipt,
  Recycle,
  Rocket,
  Route,
  Rss,
  Ruler,
  Salad,
  Satellite,
  SatelliteDish,
  Save,
  Scale,
  Scan,
  ScanSearch,
  School,
  Scissors,
  Scroll,
  ScrollText,
  Search,
  Send,
  Server,
  Settings,
  Shapes,
  Share,
  Shell,
  Shield,
  Shrub,
  Sigma,
  Signpost,
  Siren,
  Sliders,
  Smartphone,
  Smile,
  Snail,
  Snowflake,
  SolarPanel,
  Sparkles,
  Speech,
  Sprout,
  Squirrel,
  Stamp,
  Star,
  Stethoscope,
  StickyNote,
  Sun,
  Sunrise,
  Sunset,
  Syringe,
  Table,
  Tag,
  Tags,
  Target,
  Telescope,
  Terminal,
  TestTube,
  TestTubes,
  Text,
  TextQuote,
  Theater,
  Thermometer,
  ThumbsUp,
  Timer,
  Tractor,
  Trash,
  TreeDeciduous,
  TreePalm,
  TreePine,
  Trees,
  TrendingUp,
  Trophy,
  Turtle,
  Umbrella,
  University,
  Unlock,
  Upload,
  User,
  Users,
  Utensils,
  VenetianMask,
  Verified,
  Video,
  Vote,
  Wallet,
  Wand,
  Warehouse,
  Waves,
  Waypoints,
  Weight,
  Wheat,
  Wifi,
  Wind,
  Workflow,
  Worm,
  Wrench,
  Zap,
} from "lucide-react"

type IconComponent = ComponentType<{ className?: string }>

const ICONS: Record<IconName, IconComponent> = {
  activity: Activity,
  amphora: Amphora,
  anchor: Anchor,
  antenna: Antenna,
  apple: Apple,
  archive: Archive,
  "at-sign": AtSign,
  atom: Atom,
  award: Award,
  baby: Baby,
  backpack: Backpack,
  bandage: Bandage,
  banknote: Banknote,
  "bar-chart": BarChart,
  beaker: Beaker,
  bell: Bell,
  binary: Binary,
  binoculars: Binoculars,
  bird: Bird,
  bone: Bone,
  book: Book,
  "book-marked": BookMarked,
  "book-open": BookOpen,
  "book-open-check": BookOpenCheck,
  "book-text": BookText,
  bookmark: Bookmark,
  bot: Bot,
  box: Box,
  brain: Brain,
  "brain-circuit": BrainCircuit,
  "brain-cog": BrainCog,
  briefcase: Briefcase,
  "briefcase-medical": BriefcaseMedical,
  bug: Bug,
  building: Building,
  calculator: Calculator,
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  "calendar-days": CalendarDays,
  camera: Camera,
  castle: Castle,
  cat: Cat,
  "chart-bar-stacked": ChartBarStacked,
  "chart-line": ChartLine,
  "chart-network": ChartNetwork,
  "chart-pie": ChartPie,
  "chart-scatter": ChartScatter,
  "check-circle": CheckCircle,
  cherry: Cherry,
  church: Church,
  "circle-dot": CircleDot,
  "circuit-board": CircuitBoard,
  clapperboard: Clapperboard,
  clipboard: Clipboard,
  "clipboard-list": ClipboardList,
  clock: Clock,
  cloud: Cloud,
  "cloud-rain": CloudRain,
  "cloud-sun": CloudSun,
  clover: Clover,
  code: Code,
  coffee: Coffee,
  coins: Coins,
  compass: Compass,
  construction: Construction,
  contact: Contact,
  "cooking-pot": CookingPot,
  cpu: Cpu,
  crosshair: Crosshair,
  crown: Crown,
  database: Database,
  diamond: Diamond,
  dna: Dna,
  dog: Dog,
  download: Download,
  "drafting-compass": DraftingCompass,
  drama: Drama,
  droplet: Droplet,
  dumbbell: Dumbbell,
  ear: Ear,
  earth: Earth,
  "external-link": ExternalLink,
  eye: Eye,
  factory: Factory,
  feather: Feather,
  file: File,
  "file-chart-line": FileChartLine,
  "file-check": FileCheck,
  "file-code": FileCode,
  "file-search": FileSearch,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  film: Film,
  filter: Filter,
  fingerprint: Fingerprint,
  fish: Fish,
  flag: Flag,
  flame: Flame,
  "flask-conical": FlaskConical,
  "flask-round": FlaskRound,
  flower: Flower,
  focus: Focus,
  folder: Folder,
  "folder-open": FolderOpen,
  "folder-search": FolderSearch,
  footprints: Footprints,
  frown: Frown,
  funnel: Funnel,
  gauge: Gauge,
  gavel: Gavel,
  gem: Gem,
  gift: Gift,
  glasses: Glasses,
  globe: Globe,
  "graduation-cap": GraduationCap,
  grape: Grape,
  grid: Grid,
  group: Group,
  guitar: Guitar,
  hammer: Hammer,
  "hand-coins": HandCoins,
  "hand-heart": HandHeart,
  handshake: Handshake,
  "hard-drive": HardDrive,
  "hard-hat": HardHat,
  hash: Hash,
  headphones: Headphones,
  heart: Heart,
  "heart-pulse": HeartPulse,
  "help-circle": HelpCircle,
  "helping-hand": HelpingHand,
  highlighter: Highlighter,
  history: History,
  home: Home,
  hospital: Hospital,
  hourglass: Hourglass,
  image: Image,
  inbox: Inbox,
  infinity: InfinityIcon,
  info: Info,
  kanban: Kanban,
  key: Key,
  landmark: Landmark,
  languages: Languages,
  laptop: Laptop,
  layers: Layers,
  leaf: Leaf,
  lectern: Lectern,
  library: Library,
  lightbulb: Lightbulb,
  link: Link,
  list: List,
  "list-check": ListCheck,
  lock: Lock,
  mail: Mail,
  map: Map,
  "map-pin": MapPin,
  medal: Medal,
  megaphone: Megaphone,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  mic: Mic,
  microchip: Microchip,
  microscope: Microscope,
  milestone: Milestone,
  monitor: Monitor,
  moon: Moon,
  mountain: Mountain,
  music: Music,
  navigation: Navigation,
  network: Network,
  newspaper: Newspaper,
  notebook: Notebook,
  "notebook-pen": NotebookPen,
  orbit: Orbit,
  origami: Origami,
  package: Package,
  paintbrush: Paintbrush,
  palette: Palette,
  paperclip: Paperclip,
  "paw-print": PawPrint,
  pen: Pen,
  pencil: Pencil,
  percent: Percent,
  "person-standing": PersonStanding,
  phone: Phone,
  pi: Pi,
  piano: Piano,
  "piggy-bank": PiggyBank,
  pill: Pill,
  pin: Pin,
  plus: Plus,
  podcast: Podcast,
  power: Power,
  presentation: Presentation,
  printer: Printer,
  puzzle: Puzzle,
  quote: Quote,
  rabbit: Rabbit,
  radar: Radar,
  radiation: Radiation,
  radio: Radio,
  "radio-tower": RadioTower,
  rainbow: Rainbow,
  rat: Rat,
  receipt: Receipt,
  recycle: Recycle,
  rocket: Rocket,
  route: Route,
  rss: Rss,
  ruler: Ruler,
  salad: Salad,
  satellite: Satellite,
  "satellite-dish": SatelliteDish,
  save: Save,
  scale: Scale,
  scan: Scan,
  "scan-search": ScanSearch,
  school: School,
  scissors: Scissors,
  scroll: Scroll,
  "scroll-text": ScrollText,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  shapes: Shapes,
  share: Share,
  shell: Shell,
  shield: Shield,
  shrub: Shrub,
  sigma: Sigma,
  signpost: Signpost,
  siren: Siren,
  sliders: Sliders,
  smartphone: Smartphone,
  smile: Smile,
  snail: Snail,
  snowflake: Snowflake,
  "solar-panel": SolarPanel,
  sparkles: Sparkles,
  speech: Speech,
  sprout: Sprout,
  squirrel: Squirrel,
  stamp: Stamp,
  star: Star,
  stethoscope: Stethoscope,
  "sticky-note": StickyNote,
  sun: Sun,
  sunrise: Sunrise,
  sunset: Sunset,
  syringe: Syringe,
  table: Table,
  tag: Tag,
  tags: Tags,
  target: Target,
  telescope: Telescope,
  terminal: Terminal,
  "test-tube": TestTube,
  "test-tubes": TestTubes,
  text: Text,
  "text-quote": TextQuote,
  theater: Theater,
  thermometer: Thermometer,
  "thumbs-up": ThumbsUp,
  timer: Timer,
  tool: Wrench,
  tractor: Tractor,
  trash: Trash,
  "tree-deciduous": TreeDeciduous,
  "tree-palm": TreePalm,
  "tree-pine": TreePine,
  trees: Trees,
  "trending-up": TrendingUp,
  trophy: Trophy,
  turtle: Turtle,
  umbrella: Umbrella,
  university: University,
  unlock: Unlock,
  upload: Upload,
  user: User,
  users: Users,
  utensils: Utensils,
  "venetian-mask": VenetianMask,
  verified: Verified,
  video: Video,
  vote: Vote,
  wallet: Wallet,
  wand: Wand,
  warehouse: Warehouse,
  waves: Waves,
  waypoints: Waypoints,
  weight: Weight,
  wheat: Wheat,
  wifi: Wifi,
  wind: Wind,
  workflow: Workflow,
  worm: Worm,
  wrench: Wrench,
  zap: Zap,
}

export const resolveIcon = (name: string): IconComponent => ICONS[name as IconName] ?? Hash
