import { applyDiff, generateDiff } from "~/lib/diff"
import { repairJsonNewlines } from "~/lib/json"
import { parseCodeBlocks } from "~/domain/blocks"
import {
  fillMissingIds,
  buildGeneratedIdsList,
  validateMarkdownBlocks,
  extractProse,
  type ValidationContext,
  type ValidationError,
  type GeneratedId,
} from "~/domain/blocks"
import { getFiles } from "./store"
import { getAllCodes } from "./selectors"

export type FileResult =
  | { path: string; status: "ok"; content: string; generatedIds?: GeneratedId[] }
  | { path: string; status: "error"; error: string; blockErrors?: ValidationError[] }

export type MultiPatchResult = {
  results: FileResult[]
}

const isMdFile = (path: string): boolean => path.endsWith(".md")
const isJsonBlock = (language: string): boolean => language.startsWith("json")

const repairJsonBlocks = (markdown: string): string => {
  const blocks = parseCodeBlocks(markdown).filter((b) => isJsonBlock(b.language))
  if (blocks.length === 0) return markdown

  let result = markdown
  let offset = 0

  for (const block of blocks) {
    const repaired = repairJsonNewlines(block.content)
    if (repaired === block.content) continue

    const blockStart = block.start + offset
    const blockEnd = block.end + offset
    const original = result.slice(blockStart, blockEnd)
    const replaced = original.replace(block.content, repaired)

    result = result.slice(0, blockStart) + replaced + result.slice(blockEnd)
    offset += replaced.length - original.length
  }

  return result
}

const buildValidationContext = (markdown: string): ValidationContext => ({
  documentProse: extractProse(markdown),
  availableCodes: getAllCodes(getFiles()).map((c) => ({ id: c.id, name: c.title })),
})

const formatBlockErrors = (errors: ValidationError[]): string =>
  errors.map((e) => {
    const location = e.field ? `${e.block}.${e.field}` : e.block
    const hint = e.hint ? ` Available: ${JSON.stringify(e.hint)}` : ""
    const current = e.currentBlock ? `\nCurrent block:\n${e.currentBlock}` : ""
    return `${location}: ${e.message}${hint}${current}`
  }).join("\n")

type ApplyMdPatchOptions = {
  skipImmutableCheck?: boolean
  skipCodeValidation?: boolean
  placeholderIds?: Record<string, string>
}

const applyMdPatch = (path: string, content: string, patch: string, options: ApplyMdPatchOptions = {}): FileResult => {
  if (content === "" && patch === "") {
    return { path, status: "ok", content: "" }
  }

  const diffResult = applyDiff(content, patch)
  if (!diffResult.ok) {
    return { path, status: "error", error: diffResult.error }
  }

  const repairedContent = repairJsonBlocks(diffResult.content)
  const { content: filledContent, generated: autoGenerated } = fillMissingIds(repairedContent)

  const context = buildValidationContext(filledContent)
  const validation = validateMarkdownBlocks(filledContent, {
    context,
    original: content,
    skipImmutableCheck: options.skipImmutableCheck,
  })

  if (!validation.valid) {
    if (options.skipCodeValidation) {
      console.warn(`[patch] validation warnings for "${path}":`, formatBlockErrors(validation.errors))
    } else {
      return {
        path,
        status: "error",
        error: formatBlockErrors(validation.errors),
        blockErrors: validation.errors,
      }
    }
  }

  const generatedIds = buildGeneratedIdsList(options.placeholderIds ?? {}, autoGenerated, filledContent)

  return {
    path,
    status: "ok",
    content: filledContent,
    ...(generatedIds.length > 0 && { generatedIds }),
  }
}

export type ApplyFilePatchOptions = {
  skipImmutableCheck?: boolean
  skipCodeValidation?: boolean
  placeholderIds?: Record<string, string>
}

export const applyFilePatch = (path: string, content: string, patch: string, options: ApplyFilePatchOptions = {}): FileResult =>
  isMdFile(path)
    ? applyMdPatch(path, content, patch, options)
    : { path, status: "error", error: `only .md files allowed: ${path}` }

export type FilePatch = {
  path: string
  content: string
  patch: string
}

export const applyFilePatches = (patches: FilePatch[]): MultiPatchResult => ({
  results: patches.map(({ path, content, patch }) => applyFilePatch(path, content, patch)),
})

// Re-export for convenience
export { applyDiff as applyPatch } from "~/lib/diff"
export { generateDiff as computeJsonDiff } from "~/lib/diff"
