import { applyDiff, generateDiff } from "~/lib/diff"
import { expandRangeRefs, type FileReader } from "~/lib/diff/range-ref"
import { resolveFuzzyPatterns } from "~/lib/diff/fuzzy-inline"
import { repairJsonNewlines, toExtraPretty, fromExtraPretty, PrettyJsonError } from "~/lib/json"
import { stripPendingRefs } from "./pending-refs"
import { parseCodeBlocks } from "~/lib/blocks/parse"
import { fillMissingIds, buildGeneratedIdsList, type GeneratedId } from "~/lib/blocks/uuid"
import { validateMarkdownBlocks, extractProse, type ValidationError } from "~/lib/blocks/validate"
import { stampActors } from "~/lib/blocks/actor"
import type { ValidationContext } from "~/domain/blocks/registry"
import { getFiles } from "./store"
import { getAllCodes, getTagDefinitions } from "./selectors"

export type FileResult =
  | { path: string; status: "ok"; content: string; generatedIds?: GeneratedId[] }
  | { path: string; status: "error"; error: string; blockErrors?: ValidationError[] }

export type MultiPatchResult = {
  results: FileResult[]
}

const isMdFile = (path: string): boolean => path.endsWith(".md")
const isJsonBlock = (language: string): boolean => language.startsWith("json")

const repairJsonBlocks = (markdown: string): string => {
  const blocks = parseCodeBlocks(markdown).filter((b) => isJsonBlock(b.language))
  if (blocks.length === 0) return markdown

  let result = markdown
  let offset = 0

  for (const block of blocks) {
    const repaired = repairJsonNewlines(block.content)
    if (repaired === block.content) continue

    const blockStart = block.start + offset
    const blockEnd = block.end + offset
    const original = result.slice(blockStart, blockEnd)
    const replaced = original.replace(block.content, repaired)

    result = result.slice(0, blockStart) + replaced + result.slice(blockEnd)
    offset += replaced.length - original.length
  }

  return result
}

const buildValidationContext = (markdown: string): ValidationContext => ({
  documentProse: extractProse(markdown),
  availableCodes: getAllCodes(getFiles()).map((c) => ({ id: c.id, name: c.title })),
  availableTags: getTagDefinitions(getFiles()).map((t) => ({ id: t.id, label: t.label })),
})

const formatBlockErrors = (errors: ValidationError[]): string =>
  errors.map((e) => {
    const location = e.field ? `${e.block}.${e.field}` : e.block
    const hint = e.hint ? ` Available: ${JSON.stringify(e.hint)}` : ""
    const current = e.currentBlock ? `\nCurrent block:\n${e.currentBlock}` : ""
    return `${location}: ${e.message}${hint}${current}`
  }).join("\n")

type ApplyMdPatchOptions = {
  skipImmutableCheck?: boolean
  skipCodeValidation?: boolean
  placeholderIds?: Record<string, string>
  actor?: "ai" | "user"
}

export type FinalizeContentOptions = {
  original: string
  actor?: "ai" | "user"
  skipImmutableCheck?: boolean
  skipCodeValidation?: boolean
  placeholderIds?: Record<string, string>
}

const toPretty = (raw: string): string => toExtraPretty(stripPendingRefs(raw))

const buildFileReader = (currentPath: string, currentContent: string): FileReader =>
  (p) => {
    const raw = p === currentPath ? currentContent : getFiles()[p]
    return raw !== undefined ? toPretty(raw) : undefined
  }

export const finalizeContent = (path: string, content: string, options: FinalizeContentOptions): FileResult => {
  const { content: filledContent, generated: autoGenerated } = fillMissingIds(content, options.original)
  const stampedContent = options.actor
    ? stampActors(options.original, filledContent, options.actor)
    : filledContent

  const context = buildValidationContext(stampedContent)
  const validation = validateMarkdownBlocks(stampedContent, {
    path,
    context,
    original: options.original,
    skipImmutableCheck: options.skipImmutableCheck,
  })

  if (!validation.valid) {
    if (options.skipCodeValidation) {
      console.warn(`[patch] validation warnings for "${path}":`, formatBlockErrors(validation.errors))
    } else {
      return {
        path,
        status: "error",
        error: formatBlockErrors(validation.errors),
        blockErrors: validation.errors,
      }
    }
  }

  const generatedIds = buildGeneratedIdsList(options.placeholderIds ?? {}, autoGenerated, stampedContent)

  return {
    path,
    status: "ok",
    content: stampedContent,
    ...(generatedIds.length > 0 && { generatedIds }),
  }
}

const applyMdPatch = (path: string, content: string, patch: string, options: ApplyMdPatchOptions = {}): FileResult => {
  if (content === "" && patch === "") {
    return { path, status: "ok", content: "" }
  }

  const rangeResult = expandRangeRefs(patch, buildFileReader(path, content), path)
  if (!rangeResult.ok) return { path, status: "error", error: rangeResult.error }

  const { patch: resolvedPatch, unresolved } = resolveFuzzyPatterns(rangeResult.patch, content)
  if (unresolved.length > 0) {
    return { path, status: "error", error: `FUZZY patterns not found: ${unresolved.map(s => `"${s}"`).join(", ")}` }
  }

  const prettyContent = toExtraPretty(stripPendingRefs(content))
  const diffResult = applyDiff(prettyContent, resolvedPatch)
  if (!diffResult.ok) {
    return { path, status: "error", error: diffResult.error }
  }

  let collapsedContent: string
  try {
    collapsedContent = fromExtraPretty(diffResult.content)
  } catch (e) {
    if (e instanceof PrettyJsonError) {
      return { path, status: "error", error: e.message }
    }
    throw e
  }

  const repairedContent = repairJsonBlocks(collapsedContent)
  return finalizeContent(path, repairedContent, { original: content, ...options })
}

export type ApplyFilePatchOptions = {
  skipImmutableCheck?: boolean
  skipCodeValidation?: boolean
  placeholderIds?: Record<string, string>
  actor?: "ai" | "user"
}

export const applyFilePatch = (path: string, content: string, patch: string, options: ApplyFilePatchOptions = {}): FileResult =>
  isMdFile(path)
    ? applyMdPatch(path, content, patch, options)
    : { path, status: "error", error: `only .md files allowed: ${path}` }

export type FilePatch = {
  path: string
  content: string
  patch: string
}

export const applyFilePatches = (patches: FilePatch[]): MultiPatchResult => ({
  results: patches.map(({ path, content, patch }) => applyFilePatch(path, content, patch)),
})

// Re-export for convenience
export { applyDiff as applyPatch } from "~/lib/diff"
export { generateDiff as computeJsonDiff } from "~/lib/diff"
